# Generated by Django 2.1.7 on 2019-05-22 08:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import healthid.utils.app_utils.id_generator


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_image'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.CharField(default=healthid.utils.app_utils.id_generator.id_gen, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('created_at', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateField(auto_now=True)),
                ('variance_reason', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='StockCountRecord',
            fields=[
                ('id', models.CharField(default=healthid.utils.app_utils.id_generator.id_gen, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('quantity_counted', models.PositiveIntegerField(blank=True, null=True)),
                ('batch_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.BatchInfo')),
            ],
        ),
        migrations.AddField(
            model_name='stockcount',
            name='stock_count_record',
            field=models.ManyToManyField(related_name='stock_count_record', to='stock.StockCountRecord'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='stock_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.StockCountTemplate'),
        ),
    ]
