# Generated by Django 2.1.7 on 2019-07-12 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20190712_1946'),
        ('stock', '0004_auto_20190601_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransfer',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='stocktransferrecord',
            name='product',
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfers', to='products.Product'),
        ),
        migrations.AddField(
            model_name='stocktransferrecord',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfer_records', to='products.BatchInfo'),
        ),
    ]
