# Generated by Django 2.1.7 on 2019-04-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20190408_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notification_permissions',
            field=models.BooleanField(default=True),
        ),
    ]
