# Generated by Django 2.1.7 on 2019-04-11 09:09

from django.db import migrations, models
import django.db.models.deletion
import healthid.utils.app_utils.id_generator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.CharField(default=healthid.utils.app_utils.id_generator.id_gen, editable=False, max_length=9, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=244, unique=True)),
                ('time_zone', models.CharField(max_length=244, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='preference',
            name='outlet_timezone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preference.Timezone'),
        ),
    ]
