# Generated by Django 2.1.7 on 2019-04-12 05:09

from django.db import migrations, models
import django.db.models.deletion
import healthid.utils.app_utils.id_generator


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.CharField(default=healthid.utils.app_utils.id_generator.id_gen, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=244, unique=True)),
                ('symbol', models.CharField(max_length=244)),
                ('symbol_native', models.CharField(max_length=244)),
                ('decimal_digits', models.IntegerField()),
                ('rounding', models.IntegerField()),
                ('code', models.CharField(max_length=244, unique=True)),
                ('name_plural', models.CharField(max_length=244)),
            ],
        ),
        migrations.AddField(
            model_name='preference',
            name='outlet_currency',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='preference.Currency'),
            preserve_default=False,
        ),
    ]
