# Generated by Django 2.1.7 on 2019-04-16 10:27

from django.db import migrations, models
import django.db.models.deletion
import healthid.utils.app_utils.id_generator


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0002_auto_20190412_0609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vat',
            fields=[
                ('id', models.CharField(default=healthid.utils.app_utils.id_generator.id_gen, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('rate', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='preference',
            name='vat_rate',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='preference.Vat'),
            preserve_default=False,
        ),
    ]
