# Generated by Django 2.1.7 on 2019-07-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0006_auto_20190628_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesspreference',
            old_name='sell_inventory_notification',
            new_name='alert_low_inventory',
        ),
        migrations.RenameField(
            model_name='outletpreference',
            old_name='sell_inventory_notification',
            new_name='alert_low_inventory',
        ),
        migrations.AddField(
            model_name='businesspreference',
            name='alert_near_expiry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesspreference',
            name='weeks_to_start_supply_alert',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='outletpreference',
            name='alert_near_expiry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outletpreference',
            name='weeks_to_start_supply_alert',
            field=models.IntegerField(default=1),
        ),
    ]
