# Generated by Django 2.1.7 on 2019-04-16 12:26

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import healthid.utils.app_utils.id_generator


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchInfo',
            fields=[
                ('id', models.CharField(default=healthid.utils.app_utils.id_generator.id_gen, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('batch_no', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('pack_size', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity_received', models.PositiveIntegerField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('commentary', models.TextField(blank=True, null=True)),
                ('product', models.ManyToManyField(related_name='batch_info', to='products.Product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Suppliers')),
            ],
        ),
    ]
