# Generated by Django 2.1.7 on 2019-04-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_batchinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auto_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='markup',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='product',
            name='pre_tax_retail_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=28.7, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
