# Generated by Django 2.1.7 on 2019-04-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_batchinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='loyalty_weight',
            field=models.IntegerField(default=0),
        ),
    ]
