# Generated by Django 2.1.7 on 2019-04-25 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190417_1835'),
        ('products', '0003_product_loyalty_weight'),
    ]

    operations = [
    ]
