# Generated by Django 2.1.7 on 2019-04-30 11:05

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_parent'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('all_products', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
