# Generated by Django 2.1.7 on 2019-05-07 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0004_outlet_preference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_auto_20190502_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchinfo',
            name='outlet',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='outlets.Outlet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batchinfo',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
