# Generated by Django 2.1.7 on 2019-05-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190515_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(default='https://res.cloudinary.com/dojaopytm/image/upload/v1558444184/productPlaceholder.png'),
        ),
    ]
