# Generated by Django 2.1.7 on 2019-05-22 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='product',
        ),
        migrations.AddField(
            model_name='quantity',
            name='product',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='product_quantities', to='products.Product'),
            preserve_default=False,
        ),
    ]
