# Generated by Django 2.1.7 on 2019-05-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20190522_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reorder_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_point',
            field=models.IntegerField(default=0),
        ),
    ]
