# Generated by Django 2.1.7 on 2019-05-24 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0011_auto_20190523_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantity',
            name='authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approving_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quantity',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='quantity',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='product',
        ),
        migrations.AddField(
            model_name='quantity',
            name='product',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='product_quantities', to='products.Product'),
            preserve_default=False,
        ),
    ]
