# Generated by Django 2.1.7 on 2019-06-10 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20190530_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pack_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quality',
        ),
    ]
