# Generated by Django 2.1.7 on 2019-06-18 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0005_auto_20190523_1327'),
        ('products', '0015_auto_20190610_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='amount_paid',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='loyalty_weight',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='outlet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='outlets.Outlet'),
        ),
    ]
