# Generated by Django 2.1.7 on 2019-06-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20190625_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fix_vat_status',
            field=models.BooleanField(default=False),
        ),
    ]
