# Generated by Django 2.1.7 on 2019-06-28 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_fix_vat_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vat_status',
        ),
    ]
