# Generated by Django 2.1.7 on 2019-06-28 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_remove_product_vat_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='fix_vat_status',
            new_name='vat_status',
        ),
    ]
