# Generated by Django 2.1.7 on 2019-07-12 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0009_auto_20190710_0911'),
        ('products', '0022_auto_20190711_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='outlet',
        ),
        migrations.RemoveField(
            model_name='batchinfo',
            name='outlet',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='product',
        ),
        migrations.AddField(
            model_name='batchinfo',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='request_declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quantity',
            name='quantity_remaining',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quantity',
            name='request_declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='batchinfo',
            name='date_received',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='batchinfo',
            name='expiry_date',
            field=models.DateField(),
        ),
        migrations.RemoveField(
            model_name='batchinfo',
            name='product',
        ),
        migrations.AddField(
            model_name='batchinfo',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_info', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='auto_price',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='outlet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outlet_products', to='outlets.Outlet'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=244),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='product',
            name='pre_tax_retail_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_cost',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('product_name', 'manufacturer', 'outlet', 'measurement_unit')},
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('name', 'outlet')},
        ),
    ]
