# Generated by Django 2.1.7 on 2019-07-22 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0009_auto_20190710_0911'),
        ('products', '0023_auto_20190712_1946'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('product_name', 'manufacturer', 'outlet', 'description', 'measurement_unit')},
        ),
    ]
