# Generated by Django 2.1.7 on 2019-08-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20190722_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchinfo',
            name='commentary',
        ),
        migrations.RemoveField(
            model_name='batchinfo',
            name='pack_size',
        ),
        migrations.AddField(
            model_name='batchinfo',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='batchinfo',
            name='delivery_promptness',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='batchinfo',
            name='service_quality',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
