# Generated by Django 2.2 on 2019-08-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20190804_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchinfo',
            name='is_returnable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_returnable',
            field=models.BooleanField(default=True),
        ),
    ]
