# Generated by Django 2.2 on 2019-09-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_product_is_returnable'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchinfo',
            name='is_returnable',
            field=models.BooleanField(default=True),
        ),
    ]
