# Generated by Django 2.2 on 2019-11-05 13:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0028_auto_20191105_1458'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeasurementUnit',
            new_name='DispensingSize',
        ),
    ]
