# Generated by Django 2.2 on 2019-12-12 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20191202_0954'),
        ('products', '0029_auto_20191105_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Business'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('name', 'business')},
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='outlet',
        ),
    ]
