# Generated by Django 2.2 on 2019-12-12 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20191202_0954'),
        ('products', '0030_auto_20191212_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_products', to='business.Business'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('product_name', 'manufacturer', 'business', 'description', 'dispensing_size')},
        ),
        migrations.RemoveField(
            model_name='product',
            name='outlet',
        ),
    ]
