# Generated by Django 2.2 on 2020-01-10 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20191212_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMeta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataKey', models.CharField(max_length=100, null=True)),
                ('dataValue', models.CharField(max_length=100, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'unique_together': {('product', 'dataKey')},
            },
        ),
    ]
