# Generated by Django 2.2 on 2020-01-24 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_productmeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensingsize',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='backup_supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup', to='orders.Suppliers'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dispensing_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.DispensingSize'),
        ),
        migrations.AlterField(
            model_name='product',
            name='preferred_supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefered', to='orders.Suppliers'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategory'),
        ),
    ]
