# Generated by Django 2.2 on 2020-01-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_productmeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensingsize',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
