# Generated by Django 2.2 on 2020-02-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_auto_20200124_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reorder_max',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_point',
            field=models.IntegerField(default=5),
        ),
    ]
