# Generated by Django 2.2 on 2020-01-21 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_auto_20200110_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='backup_supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup', to='orders.Suppliers'),
        ),
        migrations.AlterField(
            model_name='product',
            name='preferred_supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefered', to='orders.Suppliers'),
        ),
    ]
