# Generated by Django 2.1.7 on 2019-05-28 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outlets', '0004_outlet_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('user_type', models.IntegerField(choices=[(0, 'Customer')], default=0)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('primary_mobile_number', models.CharField(max_length=100, null=True, unique=True)),
                ('secondary_mobile_number', models.CharField(max_length=100, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=244, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=244, null=True)),
                ('local_government_area', models.CharField(max_length=244, null=True)),
                ('emergency_contact_name', models.CharField(max_length=200, null=True)),
                ('emergency_contact_number', models.CharField(max_length=100, null=True)),
                ('emergency_contact_email', models.EmailField(max_length=100, null=True)),
                ('loyalty_member', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='outlets.City')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='outlets.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
