# Generated by Django 2.2 on 2020-01-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_loyalty_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='loyalty_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
