# Generated by Django 2.1.7 on 2019-03-20 09:17

from django.conf import settings
from django.db import migrations, models
import healthid.utils.app_utils.id_generator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.CharField(default=healthid.utils.app_utils.id_generator.id_gen,
                                        editable=False, max_length=9, primary_key=True, serialize=False)),
                ('trading_name', models.CharField(max_length=244)),
                ('legal_name', models.CharField(max_length=244, unique=True)),
                ('address', models.CharField(max_length=244)),
                ('phone_number', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('website', models.CharField(max_length=344)),
                ('facebook', models.CharField(max_length=344)),
                ('twitter', models.CharField(max_length=344)),
                ('instagram', models.CharField(max_length=244)),
                ('logo', models.ImageField(upload_to='logos')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
