# Generated by Django 2.1.7 on 2019-04-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='email',
            new_name='business_email',
        ),
        migrations.RemoveField(
            model_name='business',
            name='address',
        ),
        migrations.AddField(
            model_name='business',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=244),
        ),
        migrations.AddField(
            model_name='business',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=244),
        ),
        migrations.AddField(
            model_name='business',
            name='city',
            field=models.CharField(blank=True, max_length=244),
        ),
        migrations.AddField(
            model_name='business',
            name='country',
            field=models.CharField(blank=True, max_length=244),
        ),
        migrations.AddField(
            model_name='business',
            name='local_government_area',
            field=models.CharField(blank=True, max_length=244),
        ),
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.URLField(),
        ),
    ]
