# Generated by Django 2.1.7 on 2019-07-11 09:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20190523_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='user',
            field=models.ManyToManyField(related_name='businesses', to=settings.AUTH_USER_MODEL),
        ),
    ]
