# Generated by Django 2.1.7 on 2019-04-16 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outlets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('mobile_number', models.CharField(max_length=100)),
                ('rating', models.IntegerField(null=True)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('lga', models.CharField(max_length=255)),
                ('logo', models.URLField(null=True)),
                ('commentary', models.TextField(null=True)),
                ('credit_days', models.IntegerField(null=True)),
                ('supplier_id', models.CharField(max_length=9)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlets.City')),
                ('payment_terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.PaymentTerms')),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='suppliers',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Tier'),
        ),
    ]
