# Generated by Django 2.1.7 on 2019-05-13 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0004_outlet_preference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_auto_20190424_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(default='user note about this supplier')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('outlet', models.ManyToManyField(related_name='supplier_note', to='outlets.Outlet')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Suppliers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
