# Generated by Django 2.1.7 on 2019-05-14 15:58

from django.db import migrations, models
import healthid.utils.app_utils.id_generator


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0004_outlet_preference'),
        ('orders', '0003_suppliernote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(default=healthid.utils.app_utils.id_generator.id_gen, editable=False, max_length=9)),
                ('name', models.TextField()),
                ('product_autofill', models.BooleanField(default=True)),
                ('supplier_autofill', models.BooleanField(default=True)),
                ('delivery_date', models.DateField()),
                ('sent_status', models.BooleanField(default=False)),
                ('destination_outlet', models.ManyToManyField(to='outlets.Outlet')),
            ],
        ),
    ]
