# Generated by Django 2.1.7 on 2019-06-12 12:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20190530_0124'),
        ('outlets', '0005_auto_20190523_1327'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0006_auto_20190529_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('scanned_number', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('batch_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_scans', to='products.BatchInfo')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='barcodescan',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_scans', to='orders.Order'),
        ),
        migrations.AddField(
            model_name='barcodescan',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_scans', to='outlets.Outlet'),
        ),
        migrations.AddField(
            model_name='barcodescan',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_scans', to='products.Product'),
        ),
    ]
