# Generated by Django 2.1.7 on 2019-06-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20190610_1800'),
        ('orders', '0007_auto_20190612_1333'),
    ]

    operations = [
    ]
