# Generated by Django 2.1.7 on 2019-06-13 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190612_1611'),
        ('orders', '0008_merge_20190612_1517'),
    ]

    operations = [
    ]
