# Generated by Django 2.1.7 on 2019-06-18 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_merge_20190613_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='destination_outlet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='outlets.Outlet'),
        ),
    ]
