# Generated by Django 2.1.7 on 2019-06-25 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0011_auto_20190619_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorderdetails',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierorderdetails',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_supplier_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
