# Generated by Django 2.1.7 on 2019-06-26 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20190625_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='order',
            name='approved_by',
        ),
    ]
