# Generated by Django 2.1.7 on 2019-07-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20190626_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcodescan',
            name='outlet',
        ),
        migrations.RemoveField(
            model_name='barcodescan',
            name='product',
        ),
    ]
