# Generated by Django 2.1.7 on 2019-07-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20190707_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorderdetails',
            name='mark_sent',
            field=models.BooleanField(default=False),
        ),
    ]
