# Generated by Django 2.1.7 on 2019-07-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_supplierorderdetails_mark_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierorderdetails',
            old_name='mark_sent',
            new_name='marked_as_sent',
        ),
        migrations.AddField(
            model_name='supplierorderdetails',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('open', 'Open'), ('closed', 'Closed')], default='pending', max_length=10),
        ),
    ]
