# Generated by Django 2.2 on 2019-11-04 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0009_auto_20190710_0911'),
        ('orders', '0016_auto_20190719_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='outlets.Country'),
            preserve_default=False,
        ),
    ]
