# Generated by Django 2.2 on 2019-11-18 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_supplierrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='quantity',
            new_name='ordered_quantity',
        ),
    ]
