# Generated by Django 2.2 on 2019-11-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_supplierrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorderdetails',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('open', 'Open'), ('closed', 'Closed'), ('approved', 'Approved')], default='pending', max_length=10),
        ),
    ]
