# Generated by Django 2.2 on 2019-11-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20191118_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='supplier_order_number',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
