# Generated by Django 2.2 on 2019-12-01 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outlets', '0009_auto_20190710_0911'),
        ('orders', '0021_auto_20191121_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliers',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='admin_comment',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='city',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='commentary',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='country',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='credit_days',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='email',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='lga',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='outlet',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='payment_terms',
        ),
        migrations.CreateModel(
            name='SuppliersMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('display_name', models.CharField(max_length=100, null=True, unique=True)),
                ('logo', models.URLField(null=True)),
                ('payment_terms', models.CharField(choices=[('ON_CREDIT', 'on credit'), ('CASH_ON_DELIVERY', 'cash on delivery')], max_length=100, null=True)),
                ('credit_days', models.IntegerField(null=True)),
                ('commentary', models.TextField(null=True)),
                ('admin_comment', models.TextField(null=True)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Suppliers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuppliersContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=100, null=True, unique=True)),
                ('mobile_number', models.CharField(max_length=100)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('lga', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlets.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlets.Country')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Suppliers')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
