# Generated by Django 2.2 on 2019-12-03 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20191121_2143'),
        ('orders', '0019_auto_20191118_1908'),
    ]

    operations = [
    ]
