# Generated by Django 2.2 on 2019-12-03 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_merge_20191203_1116'),
        ('orders', '0022_suppliers_business'),
    ]

    operations = [
    ]
