# Generated by Django 2.2 on 2019-12-03 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20191201_1213'),
        ('orders', '0023_merge_20191203_1729'),
    ]

    operations = [
    ]
