# Generated by Django 2.2 on 2019-12-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_merge_20191203_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierscontacts',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
