# Generated by Django 2.2 on 2019-12-17 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20191210_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierscontacts',
            name='edit_request_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suppliersmeta',
            name='edit_request_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplierscontacts',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplierscontacts',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='outlets.City'),
        ),
        migrations.AlterField(
            model_name='supplierscontacts',
            name='lga',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplierscontacts',
            name='mobile_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
