# Generated by Django 2.2 on 2019-12-17 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20191217_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierscontacts',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposedEdit', to='orders.SuppliersContacts'),
        ),
        migrations.AddField(
            model_name='suppliersmeta',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposedEdit', to='orders.SuppliersMeta'),
        ),
    ]
