# Generated by Django 2.2 on 2020-01-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_order_status'),
        ('orders', '0028_order_user'),
    ]

    operations = [
    ]
