# Generated by Django 2.2 on 2020-01-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_order_user'),
        ('orders', '0028_order_status'),
    ]

    operations = [
    ]
