# Generated by Django 2.2 on 2020-01-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_merge_20200120_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Incomplete order form', max_length=50, null=True),
        ),
    ]
