# Generated by Django 2.2 on 2020-01-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20200127_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='autofillproducts',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
