# Generated by Django 2.2 on 2020-01-30 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_auto_20200124_1202'),
        ('orders', '0030_auto_20200129_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='autofillproducts',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.Product'),
        ),
    ]
