# Generated by Django 2.2 on 2020-02-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20191202_0954'),
        ('orders', '0031_autofillproducts_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliers',
            name='business',
        ),
        migrations.AddField(
            model_name='suppliers',
            name='business',
            field=models.ManyToManyField(to='business.Business'),
        ),
    ]
