# Generated by Django 2.2 on 2020-01-15 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0004_auto_20200115_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMeta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataKey', models.CharField(max_length=100, null=True)),
                ('dataValue', models.CharField(max_length=100, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
            options={
                'unique_together': {('customer', 'dataKey')},
            },
        ),
    ]
