# Generated by Django 2.1.7 on 2019-07-03 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import healthid.utils.app_utils.id_generator


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0007_sale_loyalty_earned'),
        ('receipts', '0002_auto_20190523_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(default=healthid.utils.app_utils.id_generator.id_gen, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('receipt_no', models.CharField(max_length=50, null=True)),
                ('barcode_url', models.URLField(null=True)),
                ('scanned_number', models.BigIntegerField(null=True)),
                ('footer', models.CharField(default='Thank you for shopping with us.', max_length=244)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('receipt_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='receipts.ReceiptTemplate')),
                ('sale', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Sale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='fieldset',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='fieldset',
            name='receipt_template',
        ),
        migrations.DeleteModel(
            name='FieldSet',
        ),
    ]
