# Generated by Django 2.2 on 2019-09-02 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_batchhistory'),
        ('receipts', '0003_auto_20190703_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='sales_return',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.SaleReturn'),
        ),
    ]
