# Generated by Django 2.1.7 on 2019-05-01 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outlets', '0004_outlet_preference'),
        ('products', '0004_merge_20190425_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPrompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_title', models.CharField(max_length=244, unique=True)),
                ('description', models.CharField(default='Sales prompt descripttion:', max_length=244)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlets.Outlet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
