# Generated by Django 2.1.7 on 2019-05-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20190507_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
