# Generated by Django 2.1.7 on 2019-07-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20190711_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
