# Generated by Django 2.1.7 on 2019-08-06 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0009_auto_20190710_0911'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0003_profile_loyalty_points'),
        ('products', '0026_product_is_returnable'),
        ('sales', '0010_auto_20190726_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('return_note', models.CharField(blank=True, max_length=80)),
                ('return_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('refund_compensation_type', models.CharField(max_length=80)),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashier', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.Profile')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='outlets.Outlet')),
                ('sale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.Sale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleReturnDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('return_reason', models.CharField(max_length=80)),
                ('is_approved', models.BooleanField(default=False)),
                ('resellable', models.BooleanField(default=False)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product')),
                ('sales_return', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.SaleReturn')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
