# Generated by Django 2.2 on 2019-09-02 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0027_batchinfo_is_returnable'),
        ('sales', '0011_salereturn_salereturndetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity_taken', models.PositiveIntegerField()),
                ('batch_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_info_history', to='products.BatchInfo')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quantity_by_batches', to='products.Product')),
                ('sale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_batch_history', to='sales.Sale')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
