# Generated by Django 2.2 on 2019-11-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_auto_20190913_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='applied_date',
            field=models.DateField(null=True),
        ),
    ]
