# Generated by Django 2.2 on 2019-11-18 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_batchinfo_is_returnable'),
        ('sales', '0013_auto_20190913_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salereturndetail',
            name='product',
        ),
        migrations.AddField(
            model_name='salereturndetail',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.BatchInfo'),
        ),
    ]
