# Generated by Django 2.2 on 2019-11-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_auto_20191118_1523'),
        ('sales', '0014_promotion_applied_date'),
    ]

    operations = [
    ]
