# Generated by Django 2.2 on 2019-12-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_merge_20191122_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Card', 'Card')], max_length=6),
        ),
    ]
