# Generated by Django 2.1.7 on 2019-03-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='prefix_id',
            field=models.CharField(default='1', max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outlet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
