# Generated by Django 2.1.7 on 2019-04-04 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outlets', '0002_auto_20190329_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='user',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
