# Generated by Django 2.1.7 on 2019-04-11 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0001_initial'),
        ('outlets', '0003_outlet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='preference',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='preference.Preference'),
        ),
    ]
