# Generated by Django 2.1.7 on 2019-06-13 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0005_auto_20190523_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlet',
            name='preference',
        ),
    ]
