# Generated by Django 2.1.7 on 2019-07-10 08:08

from django.db import migrations


def create_through_relations(apps, schema_editor):
    Outlet = apps.get_model('outlets', 'Outlet')
    OutletUser = apps.get_model('outlets', 'OutletUser')
    for outlet in Outlet.objects.all():
        for user in outlet.user.all():
            OutletUser(user=user, outlet=outlet).save()


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0007_outletuser'),
    ]

    operations = [
        migrations.RunPython(create_through_relations, reverse_code=migrations.RunPython.noop)
    ]
