# Generated by Django 2.1.7 on 2019-07-10 08:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outlets', '0008_auto_20190710_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlet',
            name='user',
        ),
        migrations.AddField(
            model_name='outlet',
            name='users',
            field=models.ManyToManyField(related_name='outlets', through='outlets.OutletUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
