# Generated by Django 2.2 on 2019-12-09 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20190523_1327'),
        ('outlets', '0009_auto_20190710_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlet',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='outlet',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='outlet',
            name='date_launched',
        ),
        migrations.RemoveField(
            model_name='outlet',
            name='lga',
        ),
        migrations.RemoveField(
            model_name='outlet',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='outlet',
            name='prefix_id',
        ),
        migrations.AddField(
            model_name='outletuser',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Role'),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='outlets.City'),
        ),
        migrations.CreateModel(
            name='OutletMeta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataKey', models.CharField(max_length=100, null=True)),
                ('dataValue', models.CharField(max_length=100, null=True)),
                ('outlet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='outlets.Outlet')),
            ],
            options={
                'unique_together': {('outlet', 'dataKey')},
            },
        ),
        migrations.CreateModel(
            name='OutletContacts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataKey', models.CharField(max_length=100, null=True)),
                ('dataValue', models.CharField(max_length=100, null=True)),
                ('outlet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='outlets.Outlet')),
            ],
            options={
                'unique_together': {('outlet', 'dataKey')},
            },
        ),
    ]
