#!/bin/bash
#
# A hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# Check that there are no failing tests before committing
python manage.py test
flake8
if [ $? -eq 0 ]; then
    # tests passed, proceed to prepare commit message
    exit 0
else
    # some tests failed, prevent from committing broken code on master
    echo "Some tests failed. You are not allowed to commit broken code! Aborting the commit."
    exit 1
fi
