CUSTOMERS_INCLUDE_CSV_FIELDS = ['first_name',
                                'last_name',
                                'primary_mobile_number',
                                'secondary_mobile_number',
                                'email',
                                'loyalty_member',
                                'address_line_1',
                                'address_line_2',
                                'country',
                                'city',
                                'region',
                                'emergency_contact_name',
                                'emergency_contact_number',
                                'emergency_contact_email']
