# Generated by Django 2.1.7 on 2019-05-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event_name',
            field=models.CharField(default='general_notification', max_length=100),
        ),
    ]
