# Generated by Django 2.1.7 on 2019-05-02 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import healthid.utils.app_utils.id_generator


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_auto_20190501_1116'),
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleConsultation',
            fields=[
                ('id', models.CharField(default=healthid.utils.app_utils.id_generator.id_gen, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('payment_status', models.CharField(default='Not Paid', max_length=100)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('consultants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('consultation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.Consultation')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
