# Generated by Django 2.1.7 on 2019-08-01 11:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationcatalogue',
            name='approved_delivery_formats',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('In_Person', 'In Person'), ('Telephonic', 'Telephonic'), ('Video_Conferencing', 'Video Conferencing')], default='In_Person', max_length=50), size=None),
        ),
        migrations.AlterField(
            model_name='consultationcatalogue',
            name='consultant_role',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Health_Coach', 'Health Coach'), ('Pharmacist', 'Pharmacist'), ('Sales_Person', 'Sales Associate')], default='Pharmacist', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerconsultation',
            name='status',
            field=models.CharField(choices=[('Now', 'Now'), ('Done', 'Already Completed'), ('Later', 'Later')], default='Now', max_length=10),
        ),
    ]
